Hormone Levels Trend

In [1]:
# Import dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Hormone Levels Trends Dataset
df = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\hormone levels trends\hormone_levels_trends.csv")

In [3]:
# Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Record_ID                 8000 non-null   object
 1   Age                       8000 non-null   int64
 2   Year                      8000 non-null   int64
 3   Testosterone_Level_ng_dl  8000 non-null   float64
 4   Estrogen_Level_pmol_l     8000 non-null   float64
 5   BMI                       8000 non-null   float64
 6   Exercise_Frequency        6401 non-null   object
 7   Stress_Level              8000 non-null   object
 8   Smoking_Status            8000 non-null   object
 9   Alcohol_Consumption       4775 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 625.1+ KB

In [4]:
#Checking the dataset
df.head(10)

,Record_ID,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,R00001,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
1,R00002,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
2,R00003,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,R00004,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,R00005,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,R00006,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
6,R00007,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
7,R00008,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,R00009,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
9,R00010,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [5]:
#Dropping Unnecessary columns
df = df.drop(columns=['Record_ID'])

In [6]:
#Checking Updated dataset
df.head(10)

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
2,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
7,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
9,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [7]:
#Checking for missing values
print(df.isnull().sum())

Age                            0
Year                           0
Testosterone_Level_ng_dl       0
Estrogen_Level_pmol_l          0
BMI                            0
Exercise_Frequency          1599
Stress_Level                   0
Smoking_Status                 0
Alcohol_Consumption         3225
dtype: int64

In [8]:
#Checking Exercise_Frequency rows for missing values
df[df['Exercise_Frequency'].isnull()]

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
5,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
8,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
14,41,2000,557.2,31.7,20.3,NaN,Moderate,Current Smoker,Regular
19,61,2012,563.3,43.9,24.3,NaN,Low,Non-Smoker,NaN
...,...,...,...,...,...,...,...,...,...
7982,34,2020,537.8,48.1,27.0,NaN,Low,Current Smoker,Occasional
7987,58,2011,567.2,34.5,26.9,NaN,Moderate,Current Smoker,NaN
7992,60,2013,515.9,46.8,34.6,NaN,Moderate,Non-Smoker,Occasional
7996,60,2018,482.4,43.5,25.3,NaN,High,Non-Smoker,NaN
7997,20,2011,527.9,35.3,31.5,NaN,High,Non-Smoker,NaN

In [9]:
#Changing all missing values in Exercise_Type to 'None'
df['Exercise_Frequency'] = df['Exercise_Frequency'].fillna('None')

In [10]:
#Checking Alcohol_Consumption rows for missing values
df[df['Alcohol_Consumption'].isnull()]

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,38,2012,527.7,35.4,21.6,None,Moderate,Non-Smoker,NaN
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
11,41,2012,550.7,41.9,18.5,Moderate,High,Non-Smoker,NaN
...,...,...,...,...,...,...,...,...,...
7985,52,2008,607.1,31.5,25.1,Low,High,Non-Smoker,NaN
7987,58,2011,567.2,34.5,26.9,None,Moderate,Current Smoker,NaN
7996,60,2018,482.4,43.5,25.3,None,High,Non-Smoker,NaN
7997,20,2011,527.9,35.3,31.5,None,High,Non-Smoker,NaN
7998,52,2001,599.4,31.5,23.7,Moderate,Moderate,Non-Smoker,NaN

In [11]:
#Changing all missing values in Exercise_Type to 'None'
df['Alcohol_Consumption'] = df['Alcohol_Consumption'].fillna('None')

In [12]:
#checking the results of the changes
df.head(10)

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,None,Moderate,Non-Smoker,Occasional
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,None
2,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,None
5,38,2012,527.7,35.4,21.6,None,Moderate,Non-Smoker,None
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,None
7,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,40,2020,561.6,47.4,30.1,None,Low,Non-Smoker,Occasional
9,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [13]:
# Checking the results of the changes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       8000 non-null   int64
 1   Year                      8000 non-null   int64
 2   Testosterone_Level_ng_dl  8000 non-null   float64
 3   Estrogen_Level_pmol_l     8000 non-null   float64
 4   BMI                       8000 non-null   float64
 5   Exercise_Frequency        8000 non-null   object
 6   Stress_Level              8000 non-null   object
 7   Smoking_Status            8000 non-null   object
 8   Alcohol_Consumption       8000 non-null   object
dtypes: float64(3), int64(2), object(4)
memory usage: 562.6+ KB