Mental Health x Physical Activity

In [1]:
# Import dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Mental Health x Physical Activity
df = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Mental Health x Physical Activity\mental_health_physical_activity.csv")

Mealth Health X Physical Acticity Dataset

In [3]:
# Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   300 non-null    int64
 1   Age                  300 non-null    int64
 2   Gender               300 non-null    object
 3   Occupation           300 non-null    object
 4   Sleep_Hours          300 non-null    float64
 5   Daily_Steps          300 non-null    int64
 6   Exercise_Frequency   300 non-null    int64
 7   Exercise_Duration    300 non-null    float64
 8   Exercise_Type        252 non-null    object
 9   Screen_Time_Hours    300 non-null    float64
 10  Diet_Quality         300 non-null    int64
 11  Social_Interaction   300 non-null    int64
 12  Stress_Level         300 non-null    int64
 13  Anxiety_Level        300 non-null    int64
 14  Depression_Level     300 non-null    int64
 15  Happiness_Level      300 non-null    int64
 16  Mental_Health_Score  300 non-null    float64
 17  Notes                0 non-null      float64
dtypes: float64(5), int64(10), object(3)
memory usage: 42.3+ KB

In [4]:
df.head(10)

,ID,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score,Notes
0,1,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0,NaN
1,2,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7,NaN
2,3,62,Female,Unemployed,5.4,4527,5,9.2,Sports,1.9,3,19,5,1,8,9,13.3,NaN
3,4,25,Female,Student,6.8,14588,5,52.0,NaN,1.6,2,9,2,4,2,7,11.3,NaN
4,5,35,Female,Unemployed,4.8,6820,3,60.3,NaN,9.4,1,19,3,9,4,3,0.7,NaN
5,6,47,Female,Unemployed,8.9,11485,3,61.6,Cardio,3.1,1,10,7,5,2,4,3.3,NaN
6,7,54,Other,Unemployed,5.1,9179,6,79.6,NaN,5.1,3,4,4,9,9,5,2.7,NaN
7,8,65,Other,Retired,8.5,7543,5,19.7,Strength,5.6,1,1,2,3,3,7,11.3,NaN
8,9,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7,NaN
9,10,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0,NaN

In [5]:
# Drop any unnecessary columns and variables
df = df.drop(columns=['ID', 'Notes'])

df = df[~df['Gender'].isin(['Female', 'Other'])]

In [6]:
# Checking the results of the changes
df.head(10)

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
0,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0
1,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7
8,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7
9,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0
13,32,Male,Unemployed,4.1,10075,3,53.0,Cardio,1.6,1,7,2,1,6,2,1.0
14,50,Male,Unemployed,7.3,4510,2,65.1,Mixed,6.2,2,15,7,4,2,2,-0.3
16,30,Male,Retired,4.7,4006,4,41.6,Cardio,5.0,5,3,1,9,1,2,0.3
17,33,Male,Retired,6.4,4502,6,81.2,Strength,4.4,4,8,8,5,7,9,11.3
20,56,Male,Student,6.1,10562,5,84.1,Strength,7.0,3,7,5,7,3,5,5.0
26,61,Male,Student,5.8,10173,6,87.6,NaN,2.4,2,5,3,7,1,3,2.3

In [7]:
# Check for missing values
print(df.isnull().sum())

Age                     0
Gender                  0
Occupation              0
Sleep_Hours             0
Daily_Steps             0
Exercise_Frequency      0
Exercise_Duration       0
Exercise_Type          16
Screen_Time_Hours       0
Diet_Quality            0
Social_Interaction      0
Stress_Level            0
Anxiety_Level           0
Depression_Level        0
Happiness_Level         0
Mental_Health_Score     0
dtype: int64

In [8]:
# Summary of changed dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 298
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  89 non-null     int64
 1   Gender               89 non-null     object
 2   Occupation           89 non-null     object
 3   Sleep_Hours          89 non-null     float64
 4   Daily_Steps          89 non-null     int64
 5   Exercise_Frequency   89 non-null     int64
 6   Exercise_Duration    89 non-null     float64
 7   Exercise_Type        73 non-null     object
 8   Screen_Time_Hours    89 non-null     float64
 9   Diet_Quality         89 non-null     int64
 10  Social_Interaction   89 non-null     int64
 11  Stress_Level         89 non-null     int64
 12  Anxiety_Level        89 non-null     int64
 13  Depression_Level     89 non-null     int64
 14  Happiness_Level      89 non-null     int64
 15  Mental_Health_Score  89 non-null     float64
dtypes: float64(4), int64(9), object(3)
memory usage: 11.8+ KB

In [9]:
#Checking rows with missing values 
df[df['Exercise_Type'].isnull()]

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
1,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7
26,61,Male,Student,5.8,10173,6,87.6,NaN,2.4,2,5,3,7,1,3,2.3
34,30,Male,Student,4.2,8784,1,41.0,NaN,6.2,4,15,7,4,3,1,-2.7
39,48,Male,Unemployed,5.5,7389,6,48.4,NaN,5.9,5,7,8,4,5,7,8.3
119,59,Male,Unemployed,5.8,13793,0,0.0,NaN,4.0,1,11,7,7,8,7,6.7
120,39,Male,Retired,7.5,7018,4,72.1,NaN,4.8,4,19,3,9,5,6,6.3
129,50,Male,Student,6.6,5982,2,14.6,NaN,3.0,5,9,2,5,4,9,14.3
146,33,Male,Working Professional,7.2,1860,1,37.2,NaN,5.3,2,0,9,3,7,8,9.7
161,52,Male,Student,4.7,5739,3,73.4,NaN,6.2,5,19,6,4,5,3,1.0
179,36,Male,Student,4.4,3526,6,64.1,NaN,2.4,4,10,6,2,2,1,-1.3
186,62,Male,Retired,7.4,3280,4,21.8,NaN,2.4,4,12,2,8,10,8,9.3
202,59,Male,Working Professional,5.2,12655,5,74.6,NaN,4.5,2,18,5,7,7,8,9.7
235,55,Male,Working Professional,4.5,11762,3,24.0,NaN,1.5,2,18,7,6,3,3,0.7
268,47,Male,Unemployed,8.3,3954,1,43.9,NaN,9.9,3,20,1,1,8,5,6.7
282,20,Male,Unemployed,7.3,1202,3,88.0,NaN,8.9,5,16,10,2,7,4,1.7
288,62,Male,Student,8.5,9067,2,74.0,NaN,7.5,1,8,10,4,4,2,-2.0

In [10]:
#Changing all missing values in Exercise_Type to 'None'
df['Exercise_Type'] = df['Exercise_Type'].fillna('None')

In [11]:
#Checking the results of the changes
df.head(10)

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
0,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0
1,23,Male,Working Professional,6.5,1434,3,64.4,None,5.9,2,14,10,5,1,3,0.7
8,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7
9,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0
13,32,Male,Unemployed,4.1,10075,3,53.0,Cardio,1.6,1,7,2,1,6,2,1.0
14,50,Male,Unemployed,7.3,4510,2,65.1,Mixed,6.2,2,15,7,4,2,2,-0.3
16,30,Male,Retired,4.7,4006,4,41.6,Cardio,5.0,5,3,1,9,1,2,0.3
17,33,Male,Retired,6.4,4502,6,81.2,Strength,4.4,4,8,8,5,7,9,11.3
20,56,Male,Student,6.1,10562,5,84.1,Strength,7.0,3,7,5,7,3,5,5.0
26,61,Male,Student,5.8,10173,6,87.6,None,2.4,2,5,3,7,1,3,2.3

In [12]:
# Checking the results of the changes
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 298
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  89 non-null     int64
 1   Gender               89 non-null     object
 2   Occupation           89 non-null     object
 3   Sleep_Hours          89 non-null     float64
 4   Daily_Steps          89 non-null     int64
 5   Exercise_Frequency   89 non-null     int64
 6   Exercise_Duration    89 non-null     float64
 7   Exercise_Type        89 non-null     object
 8   Screen_Time_Hours    89 non-null     float64
 9   Diet_Quality         89 non-null     int64
 10  Social_Interaction   89 non-null     int64
 11  Stress_Level         89 non-null     int64
 12  Anxiety_Level        89 non-null     int64
 13  Depression_Level     89 non-null     int64
 14  Happiness_Level      89 non-null     int64
 15  Mental_Health_Score  89 non-null     float64
dtypes: float64(4), int64(9), object(3)
memory usage: 11.8+ KB