Stress Level Prediction

In [1]:
# Import dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Stress Level Prediction Dataset
df = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Stress Level Prediction\stress_detection_data.csv")

In [3]:
# Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  773 non-null    int64
 1   Gender               773 non-null    object
 2   Occupation           773 non-null    object
 3   Marital_Status       773 non-null    object
 4   Sleep_Duration       773 non-null    float64
 5   Sleep_Quality        773 non-null    float64
 6   Wake_Up_Time         773 non-null    object
 7   Bed_Time             773 non-null    object
 8   Physical_Activity    773 non-null    float64
 9   Screen_Time          773 non-null    float64
 10  Caffeine_Intake      773 non-null    int64
 11  Alcohol_Intake       773 non-null    int64
 12  Smoking_Habit        773 non-null    object
 13  Work_Hours           773 non-null    int64
 14  Travel_Time          773 non-null    float64
 15  Social_Interactions  773 non-null    int64
 16  Meditation_Practice  773 non-null    object
 17  Exercise_Type        773 non-null    object
 18  Blood_Pressure       773 non-null    int64
 19  Cholesterol_Level    773 non-null    int64
 20  Blood_Sugar_Level    773 non-null    int64
 21  Stress_Detection     773 non-null    object
dtypes: float64(5), int64(8), object(9)
memory usage: 133.0+ KB

In [4]:
#Checking dataset
df.head(10)

,Age,Gender,Occupation,Marital_Status,Sleep_Duration,Sleep_Quality,Wake_Up_Time,Bed_Time,Physical_Activity,Screen_Time,...,Smoking_Habit,Work_Hours,Travel_Time,Social_Interactions,Meditation_Practice,Exercise_Type,Blood_Pressure,Cholesterol_Level,Blood_Sugar_Level,Stress_Detection
0,30,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
1,35,Female,Marketing Manager,Married,6.0,3.0,6:00 AM,11:00 PM,1.0,3.0,...,No,9,2.0,3,No,Yoga,110,160,80,Medium
2,40,Male,Data Scientist,Divorced,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Strength Training,130,200,100,High
3,35,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
4,29,Female,Teacher,Single,8.0,5.0,6:30 AM,10:30 PM,3.0,2.0,...,No,7,1.0,4,Yes,Yoga,110,180,90,Low
5,45,Male,Doctor,Married,6.0,3.0,5:30 AM,11:00 PM,2.0,4.0,...,Yes,10,2.0,3,No,Cardio,130,220,110,High
6,32,Female,Graphic Designer,Single,7.0,4.0,7:00 AM,12:00 AM,1.0,6.0,...,No,9,0.5,2,No,Aerobics,120,190,85,Medium
7,37,Male,Civil Engineer,Married,7.5,4.0,6:00 AM,10:30 PM,2.5,3.5,...,No,8,1.5,5,Yes,Strength Training,140,210,100,Medium
8,50,Male,Business Owner,Married,5.5,2.0,5:00 AM,12:30 AM,2.0,8.0,...,Yes,12,2.0,2,No,Walking,150,240,130,High
9,40,Female,Nurse,Divorced,6.0,3.0,6:00 AM,11:30 PM,3.0,4.5,...,No,9,1.0,4,Yes,Pilates,125,200,105,Medium

In [5]:
#Dropping unnecessary Female Variables from the Gender column
df = df[df['Gender'] != 'Female']

In [6]:
#Checking updated dataset
df.head(10)

,Age,Gender,Occupation,Marital_Status,Sleep_Duration,Sleep_Quality,Wake_Up_Time,Bed_Time,Physical_Activity,Screen_Time,...,Smoking_Habit,Work_Hours,Travel_Time,Social_Interactions,Meditation_Practice,Exercise_Type,Blood_Pressure,Cholesterol_Level,Blood_Sugar_Level,Stress_Detection
0,30,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
2,40,Male,Data Scientist,Divorced,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Strength Training,130,200,100,High
3,35,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
5,45,Male,Doctor,Married,6.0,3.0,5:30 AM,11:00 PM,2.0,4.0,...,Yes,10,2.0,3,No,Cardio,130,220,110,High
7,37,Male,Civil Engineer,Married,7.5,4.0,6:00 AM,10:30 PM,2.5,3.5,...,No,8,1.5,5,Yes,Strength Training,140,210,100,Medium
8,50,Male,Business Owner,Married,5.5,2.0,5:00 AM,12:30 AM,2.0,8.0,...,Yes,12,2.0,2,No,Walking,150,240,130,High
10,34,Male,Software Developer,Single,6.5,4.0,6:30 AM,11:00 PM,2.0,7.0,...,No,8,1.5,3,No,Cardio,135,195,95,Medium
12,42,Male,Architect,Married,5.0,2.0,6:00 AM,12:00 AM,1.0,6.0,...,Yes,10,2.0,2,No,Strength Training,145,230,120,High
14,38,Male,Lawyer,Single,7.0,4.0,6:00 AM,11:00 PM,2.0,4.0,...,Yes,10,1.0,3,No,Cardio,130,210,100,Medium
16,43,Male,Engineer,Married,7.0,4.0,7:00 AM,11:00 PM,1.5,6.0,...,No,9,1.0,4,Yes,Strength Training,135,220,115,Medium

In [7]:
# Check for missing values
print(df.isnull().sum())

Age                    0
Gender                 0
Occupation             0
Marital_Status         0
Sleep_Duration         0
Sleep_Quality          0
Wake_Up_Time           0
Bed_Time               0
Physical_Activity      0
Screen_Time            0
Caffeine_Intake        0
Alcohol_Intake         0
Smoking_Habit          0
Work_Hours             0
Travel_Time            0
Social_Interactions    0
Meditation_Practice    0
Exercise_Type          0
Blood_Pressure         0
Cholesterol_Level      0
Blood_Sugar_Level      0
Stress_Detection       0
dtype: int64