Importing the first 4 datasets

In [107]:
# Import dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [108]:
# Loading the datasets

# Mental Health x Physical Activity
df = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Mental Health x Physical Activity\mental_health_physical_activity.csv")

# Hormone Levels Trends
df2 = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\hormone levels trends\hormone_levels_trends.csv")

# Stress Level Prediction
df3 = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Stress Level Prediction\stress_detection_data.csv")

# Testosterone and Diversity - Individual
df4 = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Testosterone and Diversity\hormone-diversity-individual.csv")

Mealth Health X Physical Acticity Dataset

In [109]:
# Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   300 non-null    int64
 1   Age                  300 non-null    int64
 2   Gender               300 non-null    object
 3   Occupation           300 non-null    object
 4   Sleep_Hours          300 non-null    float64
 5   Daily_Steps          300 non-null    int64
 6   Exercise_Frequency   300 non-null    int64
 7   Exercise_Duration    300 non-null    float64
 8   Exercise_Type        252 non-null    object
 9   Screen_Time_Hours    300 non-null    float64
 10  Diet_Quality         300 non-null    int64
 11  Social_Interaction   300 non-null    int64
 12  Stress_Level         300 non-null    int64
 13  Anxiety_Level        300 non-null    int64
 14  Depression_Level     300 non-null    int64
 15  Happiness_Level      300 non-null    int64
 16  Mental_Health_Score  300 non-null    float64
 17  Notes                0 non-null      float64
dtypes: float64(5), int64(10), object(3)
memory usage: 42.3+ KB

In [110]:
df.head(10)

,ID,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score,Notes
0,1,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0,NaN
1,2,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7,NaN
2,3,62,Female,Unemployed,5.4,4527,5,9.2,Sports,1.9,3,19,5,1,8,9,13.3,NaN
3,4,25,Female,Student,6.8,14588,5,52.0,NaN,1.6,2,9,2,4,2,7,11.3,NaN
4,5,35,Female,Unemployed,4.8,6820,3,60.3,NaN,9.4,1,19,3,9,4,3,0.7,NaN
5,6,47,Female,Unemployed,8.9,11485,3,61.6,Cardio,3.1,1,10,7,5,2,4,3.3,NaN
6,7,54,Other,Unemployed,5.1,9179,6,79.6,NaN,5.1,3,4,4,9,9,5,2.7,NaN
7,8,65,Other,Retired,8.5,7543,5,19.7,Strength,5.6,1,1,2,3,3,7,11.3,NaN
8,9,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7,NaN
9,10,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0,NaN

In [111]:
# Drop any unnecessary columns and variables
df = df.drop(columns=['ID', 'Notes'])

df = df[~df['Gender'].isin(['Female', 'Other'])]

In [112]:
# Checking the results of the changes
df.head(10)

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
0,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0
1,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7
8,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7
9,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0
13,32,Male,Unemployed,4.1,10075,3,53.0,Cardio,1.6,1,7,2,1,6,2,1.0
14,50,Male,Unemployed,7.3,4510,2,65.1,Mixed,6.2,2,15,7,4,2,2,-0.3
16,30,Male,Retired,4.7,4006,4,41.6,Cardio,5.0,5,3,1,9,1,2,0.3
17,33,Male,Retired,6.4,4502,6,81.2,Strength,4.4,4,8,8,5,7,9,11.3
20,56,Male,Student,6.1,10562,5,84.1,Strength,7.0,3,7,5,7,3,5,5.0
26,61,Male,Student,5.8,10173,6,87.6,NaN,2.4,2,5,3,7,1,3,2.3

In [113]:
# Check for missing values
print(df.isnull().sum())

Age                     0
Gender                  0
Occupation              0
Sleep_Hours             0
Daily_Steps             0
Exercise_Frequency      0
Exercise_Duration       0
Exercise_Type          16
Screen_Time_Hours       0
Diet_Quality            0
Social_Interaction      0
Stress_Level            0
Anxiety_Level           0
Depression_Level        0
Happiness_Level         0
Mental_Health_Score     0
dtype: int64

In [114]:
# Summary of changed dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 298
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  89 non-null     int64
 1   Gender               89 non-null     object
 2   Occupation           89 non-null     object
 3   Sleep_Hours          89 non-null     float64
 4   Daily_Steps          89 non-null     int64
 5   Exercise_Frequency   89 non-null     int64
 6   Exercise_Duration    89 non-null     float64
 7   Exercise_Type        73 non-null     object
 8   Screen_Time_Hours    89 non-null     float64
 9   Diet_Quality         89 non-null     int64
 10  Social_Interaction   89 non-null     int64
 11  Stress_Level         89 non-null     int64
 12  Anxiety_Level        89 non-null     int64
 13  Depression_Level     89 non-null     int64
 14  Happiness_Level      89 non-null     int64
 15  Mental_Health_Score  89 non-null     float64
dtypes: float64(4), int64(9), object(3)
memory usage: 11.8+ KB

In [115]:
#Checking rows with missing values 
df[df['Exercise_Type'].isnull()]

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
1,23,Male,Working Professional,6.5,1434,3,64.4,NaN,5.9,2,14,10,5,1,3,0.7
26,61,Male,Student,5.8,10173,6,87.6,NaN,2.4,2,5,3,7,1,3,2.3
34,30,Male,Student,4.2,8784,1,41.0,NaN,6.2,4,15,7,4,3,1,-2.7
39,48,Male,Unemployed,5.5,7389,6,48.4,NaN,5.9,5,7,8,4,5,7,8.3
119,59,Male,Unemployed,5.8,13793,0,0.0,NaN,4.0,1,11,7,7,8,7,6.7
120,39,Male,Retired,7.5,7018,4,72.1,NaN,4.8,4,19,3,9,5,6,6.3
129,50,Male,Student,6.6,5982,2,14.6,NaN,3.0,5,9,2,5,4,9,14.3
146,33,Male,Working Professional,7.2,1860,1,37.2,NaN,5.3,2,0,9,3,7,8,9.7
161,52,Male,Student,4.7,5739,3,73.4,NaN,6.2,5,19,6,4,5,3,1.0
179,36,Male,Student,4.4,3526,6,64.1,NaN,2.4,4,10,6,2,2,1,-1.3
186,62,Male,Retired,7.4,3280,4,21.8,NaN,2.4,4,12,2,8,10,8,9.3
202,59,Male,Working Professional,5.2,12655,5,74.6,NaN,4.5,2,18,5,7,7,8,9.7
235,55,Male,Working Professional,4.5,11762,3,24.0,NaN,1.5,2,18,7,6,3,3,0.7
268,47,Male,Unemployed,8.3,3954,1,43.9,NaN,9.9,3,20,1,1,8,5,6.7
282,20,Male,Unemployed,7.3,1202,3,88.0,NaN,8.9,5,16,10,2,7,4,1.7
288,62,Male,Student,8.5,9067,2,74.0,NaN,7.5,1,8,10,4,4,2,-2.0

In [116]:
#Changing all missing values in Exercise_Type to 'None'
df['Exercise_Type'] = df['Exercise_Type'].fillna('None')

In [117]:
#Checking the results of the changes
df.head(10)

,Age,Gender,Occupation,Sleep_Hours,Daily_Steps,Exercise_Frequency,Exercise_Duration,Exercise_Type,Screen_Time_Hours,Diet_Quality,Social_Interaction,Stress_Level,Anxiety_Level,Depression_Level,Happiness_Level,Mental_Health_Score
0,58,Male,Student,7.7,5012,3,12.6,Cardio,7.1,5,2,10,7,1,1,-4.0
1,23,Male,Working Professional,6.5,1434,3,64.4,None,5.9,2,14,10,5,1,3,0.7
8,56,Male,Retired,5.9,8668,4,87.4,Cardio,7.1,1,17,5,6,2,5,5.7
9,45,Male,Retired,4.0,12830,4,87.5,Strength,5.6,1,20,5,9,10,4,0.0
13,32,Male,Unemployed,4.1,10075,3,53.0,Cardio,1.6,1,7,2,1,6,2,1.0
14,50,Male,Unemployed,7.3,4510,2,65.1,Mixed,6.2,2,15,7,4,2,2,-0.3
16,30,Male,Retired,4.7,4006,4,41.6,Cardio,5.0,5,3,1,9,1,2,0.3
17,33,Male,Retired,6.4,4502,6,81.2,Strength,4.4,4,8,8,5,7,9,11.3
20,56,Male,Student,6.1,10562,5,84.1,Strength,7.0,3,7,5,7,3,5,5.0
26,61,Male,Student,5.8,10173,6,87.6,None,2.4,2,5,3,7,1,3,2.3

In [118]:
# Checking the results of the changes
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 298
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  89 non-null     int64
 1   Gender               89 non-null     object
 2   Occupation           89 non-null     object
 3   Sleep_Hours          89 non-null     float64
 4   Daily_Steps          89 non-null     int64
 5   Exercise_Frequency   89 non-null     int64
 6   Exercise_Duration    89 non-null     float64
 7   Exercise_Type        89 non-null     object
 8   Screen_Time_Hours    89 non-null     float64
 9   Diet_Quality         89 non-null     int64
 10  Social_Interaction   89 non-null     int64
 11  Stress_Level         89 non-null     int64
 12  Anxiety_Level        89 non-null     int64
 13  Depression_Level     89 non-null     int64
 14  Happiness_Level      89 non-null     int64
 15  Mental_Health_Score  89 non-null     float64
dtypes: float64(4), int64(9), object(3)
memory usage: 11.8+ KB

Hormone Levels Trends Dataset

In [119]:
# Summary of the dataset
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Record_ID                 8000 non-null   object
 1   Age                       8000 non-null   int64
 2   Year                      8000 non-null   int64
 3   Testosterone_Level_ng_dl  8000 non-null   float64
 4   Estrogen_Level_pmol_l     8000 non-null   float64
 5   BMI                       8000 non-null   float64
 6   Exercise_Frequency        6401 non-null   object
 7   Stress_Level              8000 non-null   object
 8   Smoking_Status            8000 non-null   object
 9   Alcohol_Consumption       4775 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 625.1+ KB

In [120]:
#Checking the dataset
df2.head(10)

,Record_ID,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,R00001,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
1,R00002,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
2,R00003,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,R00004,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,R00005,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,R00006,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
6,R00007,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
7,R00008,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,R00009,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
9,R00010,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [121]:
#Dropping Unnecessary columns
df2 = df2.drop(columns=['Record_ID'])

In [122]:
#Checking Updated dataset
df2.head(10)

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
2,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
7,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
9,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [123]:
#Checking for missing values
print(df2.isnull().sum())

Age                            0
Year                           0
Testosterone_Level_ng_dl       0
Estrogen_Level_pmol_l          0
BMI                            0
Exercise_Frequency          1599
Stress_Level                   0
Smoking_Status                 0
Alcohol_Consumption         3225
dtype: int64

In [124]:
#Checking Exercise_Frequency rows for missing values
df2[df2['Exercise_Frequency'].isnull()]

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,NaN,Moderate,Non-Smoker,Occasional
5,38,2012,527.7,35.4,21.6,NaN,Moderate,Non-Smoker,NaN
8,40,2020,561.6,47.4,30.1,NaN,Low,Non-Smoker,Occasional
14,41,2000,557.2,31.7,20.3,NaN,Moderate,Current Smoker,Regular
19,61,2012,563.3,43.9,24.3,NaN,Low,Non-Smoker,NaN
...,...,...,...,...,...,...,...,...,...
7982,34,2020,537.8,48.1,27.0,NaN,Low,Current Smoker,Occasional
7987,58,2011,567.2,34.5,26.9,NaN,Moderate,Current Smoker,NaN
7992,60,2013,515.9,46.8,34.6,NaN,Moderate,Non-Smoker,Occasional
7996,60,2018,482.4,43.5,25.3,NaN,High,Non-Smoker,NaN
7997,20,2011,527.9,35.3,31.5,NaN,High,Non-Smoker,NaN

In [125]:
#Changing all missing values in Exercise_Type to 'None'
df2['Exercise_Frequency'] = df2['Exercise_Frequency'].fillna('None')

In [126]:
#Checking Alcohol_Consumption rows for missing values
df2[df2['Alcohol_Consumption'].isnull()]

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,NaN
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,NaN
5,38,2012,527.7,35.4,21.6,None,Moderate,Non-Smoker,NaN
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,NaN
11,41,2012,550.7,41.9,18.5,Moderate,High,Non-Smoker,NaN
...,...,...,...,...,...,...,...,...,...
7985,52,2008,607.1,31.5,25.1,Low,High,Non-Smoker,NaN
7987,58,2011,567.2,34.5,26.9,None,Moderate,Current Smoker,NaN
7996,60,2018,482.4,43.5,25.3,None,High,Non-Smoker,NaN
7997,20,2011,527.9,35.3,31.5,None,High,Non-Smoker,NaN
7998,52,2001,599.4,31.5,23.7,Moderate,Moderate,Non-Smoker,NaN

In [127]:
#Changing all missing values in Exercise_Type to 'None'
df2['Alcohol_Consumption'] = df2['Alcohol_Consumption'].fillna('None')

In [ ]:
#checking the results of the changes
df2.head(10)

,Age,Year,Testosterone_Level_ng_dl,Estrogen_Level_pmol_l,BMI,Exercise_Frequency,Stress_Level,Smoking_Status,Alcohol_Consumption
0,56,2023,520.2,43.2,20.3,None,Moderate,Non-Smoker,Occasional
1,46,2004,611.5,30.1,22.8,Low,Low,Current Smoker,None
2,32,2019,466.2,48.6,18.1,Low,Moderate,Non-Smoker,Regular
3,60,2006,551.3,37.9,29.8,Low,Moderate,Current Smoker,Regular
4,25,2006,563.0,31.3,27.1,Low,Low,Current Smoker,None
5,38,2012,527.7,35.4,21.6,None,Moderate,Non-Smoker,None
6,56,2008,521.6,38.6,23.0,Moderate,Moderate,Non-Smoker,None
7,36,2024,516.6,47.7,28.0,Moderate,Moderate,Former Smoker,Regular
8,40,2020,561.6,47.4,30.1,None,Low,Non-Smoker,Occasional
9,28,2012,551.6,38.8,25.4,Low,High,Non-Smoker,Occasional

In [129]:
# Checking the results of the changes
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       8000 non-null   int64
 1   Year                      8000 non-null   int64
 2   Testosterone_Level_ng_dl  8000 non-null   float64
 3   Estrogen_Level_pmol_l     8000 non-null   float64
 4   BMI                       8000 non-null   float64
 5   Exercise_Frequency        8000 non-null   object
 6   Stress_Level              8000 non-null   object
 7   Smoking_Status            8000 non-null   object
 8   Alcohol_Consumption       8000 non-null   object
dtypes: float64(3), int64(2), object(4)
memory usage: 562.6+ KB

Stress Level prediction

In [130]:
# Summary of the dataset
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  773 non-null    int64
 1   Gender               773 non-null    object
 2   Occupation           773 non-null    object
 3   Marital_Status       773 non-null    object
 4   Sleep_Duration       773 non-null    float64
 5   Sleep_Quality        773 non-null    float64
 6   Wake_Up_Time         773 non-null    object
 7   Bed_Time             773 non-null    object
 8   Physical_Activity    773 non-null    float64
 9   Screen_Time          773 non-null    float64
 10  Caffeine_Intake      773 non-null    int64
 11  Alcohol_Intake       773 non-null    int64
 12  Smoking_Habit        773 non-null    object
 13  Work_Hours           773 non-null    int64
 14  Travel_Time          773 non-null    float64
 15  Social_Interactions  773 non-null    int64
 16  Meditation_Practice  773 non-null    object
 17  Exercise_Type        773 non-null    object
 18  Blood_Pressure       773 non-null    int64
 19  Cholesterol_Level    773 non-null    int64
 20  Blood_Sugar_Level    773 non-null    int64
 21  Stress_Detection     773 non-null    object
dtypes: float64(5), int64(8), object(9)
memory usage: 133.0+ KB

In [131]:
#Checking dataset
df3.head(10)

,Age,Gender,Occupation,Marital_Status,Sleep_Duration,Sleep_Quality,Wake_Up_Time,Bed_Time,Physical_Activity,Screen_Time,...,Smoking_Habit,Work_Hours,Travel_Time,Social_Interactions,Meditation_Practice,Exercise_Type,Blood_Pressure,Cholesterol_Level,Blood_Sugar_Level,Stress_Detection
0,30,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
1,35,Female,Marketing Manager,Married,6.0,3.0,6:00 AM,11:00 PM,1.0,3.0,...,No,9,2.0,3,No,Yoga,110,160,80,Medium
2,40,Male,Data Scientist,Divorced,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Strength Training,130,200,100,High
3,35,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
4,29,Female,Teacher,Single,8.0,5.0,6:30 AM,10:30 PM,3.0,2.0,...,No,7,1.0,4,Yes,Yoga,110,180,90,Low
5,45,Male,Doctor,Married,6.0,3.0,5:30 AM,11:00 PM,2.0,4.0,...,Yes,10,2.0,3,No,Cardio,130,220,110,High
6,32,Female,Graphic Designer,Single,7.0,4.0,7:00 AM,12:00 AM,1.0,6.0,...,No,9,0.5,2,No,Aerobics,120,190,85,Medium
7,37,Male,Civil Engineer,Married,7.5,4.0,6:00 AM,10:30 PM,2.5,3.5,...,No,8,1.5,5,Yes,Strength Training,140,210,100,Medium
8,50,Male,Business Owner,Married,5.5,2.0,5:00 AM,12:30 AM,2.0,8.0,...,Yes,12,2.0,2,No,Walking,150,240,130,High
9,40,Female,Nurse,Divorced,6.0,3.0,6:00 AM,11:30 PM,3.0,4.5,...,No,9,1.0,4,Yes,Pilates,125,200,105,Medium

In [132]:
#Dropping unnecessary Female Variables from the Gender column
df3 = df3[df3['Gender'] != 'Female']

In [133]:
#Checking updated dataset
df3.head(10)

,Age,Gender,Occupation,Marital_Status,Sleep_Duration,Sleep_Quality,Wake_Up_Time,Bed_Time,Physical_Activity,Screen_Time,...,Smoking_Habit,Work_Hours,Travel_Time,Social_Interactions,Meditation_Practice,Exercise_Type,Blood_Pressure,Cholesterol_Level,Blood_Sugar_Level,Stress_Detection
0,30,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
2,40,Male,Data Scientist,Divorced,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Strength Training,130,200,100,High
3,35,Male,Software Engineer,Single,7.0,4.0,7:00 AM,10:00 PM,2.0,4.0,...,No,8,1.0,5,Yes,Cardio,120,180,90,Low
5,45,Male,Doctor,Married,6.0,3.0,5:30 AM,11:00 PM,2.0,4.0,...,Yes,10,2.0,3,No,Cardio,130,220,110,High
7,37,Male,Civil Engineer,Married,7.5,4.0,6:00 AM,10:30 PM,2.5,3.5,...,No,8,1.5,5,Yes,Strength Training,140,210,100,Medium
8,50,Male,Business Owner,Married,5.5,2.0,5:00 AM,12:30 AM,2.0,8.0,...,Yes,12,2.0,2,No,Walking,150,240,130,High
10,34,Male,Software Developer,Single,6.5,4.0,6:30 AM,11:00 PM,2.0,7.0,...,No,8,1.5,3,No,Cardio,135,195,95,Medium
12,42,Male,Architect,Married,5.0,2.0,6:00 AM,12:00 AM,1.0,6.0,...,Yes,10,2.0,2,No,Strength Training,145,230,120,High
14,38,Male,Lawyer,Single,7.0,4.0,6:00 AM,11:00 PM,2.0,4.0,...,Yes,10,1.0,3,No,Cardio,130,210,100,Medium
16,43,Male,Engineer,Married,7.0,4.0,7:00 AM,11:00 PM,1.5,6.0,...,No,9,1.0,4,Yes,Strength Training,135,220,115,Medium

In [134]:
# Check for missing values
print(df3.isnull().sum())

Age                    0
Gender                 0
Occupation             0
Marital_Status         0
Sleep_Duration         0
Sleep_Quality          0
Wake_Up_Time           0
Bed_Time               0
Physical_Activity      0
Screen_Time            0
Caffeine_Intake        0
Alcohol_Intake         0
Smoking_Habit          0
Work_Hours             0
Travel_Time            0
Social_Interactions    0
Meditation_Practice    0
Exercise_Type          0
Blood_Pressure         0
Cholesterol_Level      0
Blood_Sugar_Level      0
Stress_Detection       0
dtype: int64

Testosterone and Diversity Dataset(Individual)

In [135]:
#Checking dataset
df4.head(10)

,ID,team.id,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,102,14,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
1,103,23,26.0,Female,Other,0.211,15.28,-1.555897,2.726545,USA
2,104,14,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
3,105,14,25.0,Female,South Asian,0.287,50.99,-1.248273,3.931630,India
4,107,24,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,108,16,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,111,21,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,112,18,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
8,118,24,32.0,Female,White,0.248,142.86,-1.394327,4.961865,Croatia
9,119,18,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands

In [136]:
#Dropping ID and team.id columns
df4 = df4.drop(columns=['ID', 'team.id'])

In [137]:
#Checking updated dataset
df4.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
1,26.0,Female,Other,0.211,15.28,-1.555897,2.726545,USA
2,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
3,25.0,Female,South Asian,0.287,50.99,-1.248273,3.931630,India
4,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
8,32.0,Female,White,0.248,142.86,-1.394327,4.961865,Croatia
9,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands

In [138]:
#Dropping Female variables from Gender column
df4 = df4[df4['Gender'] != 'Female']

In [139]:
#Checkin updated dataset
df4.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
2,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
4,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
9,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands
10,25.0,Male,South Asian,0.250,165.31,-1.386294,5.107822,Canada
11,33.0,Male,South Asian,0.183,87.43,-1.698269,4.470838,India
14,30.0,Male,White,0.234,138.35,-1.452434,4.929787,Switzerland

In [140]:
#Dropping every country that is not USA from the Country Column
df4 = df4[df4['Country'] == 'USA']

In [141]:
#Checking updated dataset
df4.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
17,29.0,Male,White,0.285,134.83,-1.255266,4.904015,USA
18,30.0,Male,White,0.217,115.85,-1.527858,4.752296,USA
23,31.0,Male,Other,0.195,76.11,-1.634756,4.332180,USA
25,29.0,Male,White,0.176,343.20,-1.737271,5.838313,USA
29,29.0,Male,White,0.330,251.21,-1.108663,5.526289,USA
32,24.0,Male,White,0.140,94.07,-1.966113,4.544039,USA
33,25.0,Male,White,0.183,196.77,-1.698269,5.282036,USA
34,24.0,Male,White,0.204,189.09,-1.589635,5.242223,USA

In [142]:
#Checking for missing values
print(df4.isnull().sum())

Age                 2
Gender              0
Ethnicity           0
Cortisol            0
Testosterone        0
log.cortisol        0
log.testosterone    0
Country             0
dtype: int64

In [143]:
#Dropping rows with null values
df4 = df4.dropna()

In [144]:
#Checking for missing values
print(df4.isnull().sum())

Age                 0
Gender              0
Ethnicity           0
Cortisol            0
Testosterone        0
log.cortisol        0
log.testosterone    0
Country             0
dtype: int64