Testosterone and Diversity Dataset(Individual)

In [1]:
# Import dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Testosterone and Diversity - Individual
df = pd.read_csv(r"C:\Users\crowd\Downloads\DTSC 4301 Datasets\Testosterone and Diversity\hormone-diversity-individual.csv")

In [3]:
#Checking dataset
df.head(10)

,ID,team.id,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,102,14,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
1,103,23,26.0,Female,Other,0.211,15.28,-1.555897,2.726545,USA
2,104,14,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
3,105,14,25.0,Female,South Asian,0.287,50.99,-1.248273,3.931630,India
4,107,24,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,108,16,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,111,21,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,112,18,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
8,118,24,32.0,Female,White,0.248,142.86,-1.394327,4.961865,Croatia
9,119,18,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands

In [4]:
#Dropping ID and team.id columns
df = df.drop(columns=['ID', 'team.id'])

In [5]:
#Checking updated dataset
df.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
1,26.0,Female,Other,0.211,15.28,-1.555897,2.726545,USA
2,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
3,25.0,Female,South Asian,0.287,50.99,-1.248273,3.931630,India
4,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
8,32.0,Female,White,0.248,142.86,-1.394327,4.961865,Croatia
9,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands

In [6]:
#Dropping Female variables from Gender column
df = df[df['Gender'] != 'Female']

In [7]:
#Checkin updated dataset
df.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
2,26.0,Male,Hispanic,0.152,96.21,-1.883875,4.566533,Chile
4,27.0,Male,White,0.141,178.66,-1.958995,5.185485,France
5,27.0,Male,White,0.184,87.43,-1.692820,4.470838,Italy
6,27.0,Male,Hispanic,0.329,198.54,-1.111698,5.290991,Brazil
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
9,28.0,Male,White,0.254,541.23,-1.370421,6.293844,Netherlands
10,25.0,Male,South Asian,0.250,165.31,-1.386294,5.107822,Canada
11,33.0,Male,South Asian,0.183,87.43,-1.698269,4.470838,India
14,30.0,Male,White,0.234,138.35,-1.452434,4.929787,Switzerland

In [8]:
#Dropping every country that is not USA from the Country Column
df = df[df['Country'] == 'USA']

In [9]:
#Checking updated dataset
df.head(10)

,Age,Gender,Ethnicity,Cortisol,Testosterone,log.cortisol,log.testosterone,Country
0,26.0,Male,White,0.163,134.83,-1.814005,4.904015,USA
7,30.0,Male,White,0.360,151.73,-1.021651,5.022103,USA
17,29.0,Male,White,0.285,134.83,-1.255266,4.904015,USA
18,30.0,Male,White,0.217,115.85,-1.527858,4.752296,USA
23,31.0,Male,Other,0.195,76.11,-1.634756,4.332180,USA
25,29.0,Male,White,0.176,343.20,-1.737271,5.838313,USA
29,29.0,Male,White,0.330,251.21,-1.108663,5.526289,USA
32,24.0,Male,White,0.140,94.07,-1.966113,4.544039,USA
33,25.0,Male,White,0.183,196.77,-1.698269,5.282036,USA
34,24.0,Male,White,0.204,189.09,-1.589635,5.242223,USA

In [11]:
#Checking for missing values
print(df.isnull().sum())

Age                 2
Gender              0
Ethnicity           0
Cortisol            0
Testosterone        0
log.cortisol        0
log.testosterone    0
Country             0
dtype: int64

In [12]:
#Dropping rows with null values
df = df.dropna()

In [13]:
#Checking for missing values
print(df.isnull().sum())

Age                 0
Gender              0
Ethnicity           0
Cortisol            0
Testosterone        0
log.cortisol        0
log.testosterone    0
Country             0
dtype: int64